// Auto-generated by i18n-sync.mjs. Do not edit by hand.
export default {
  "app.title": "SAVVA · SolidJS",
  "card.tailwindWorks": "Tailwind works?",
  "debug.rightOpen": "???",
  "debug.theme": "???",
  "greeting.hello": "Hello, Alex 👋",
  "rightPane.language": "Language",
  "rightPane.option1": "Option 1",
  "rightPane.option2": "Option 2",
  "rightPane.option3": "Option 3",
  "rightPane.showKeys": "Show translation keys",
  "ui.mode.dark": "Dark mode",
  "ui.mode.light": "Light mode"
};
