// Auto-generated by i18n-sync.mjs. Do not edit by hand.
export default {
  "app.title": "SAVVA · SolidJS",
  "card.tailwindWorks": "Tailwind работает?",
  "debug.rightOpen": "???",
  "debug.theme": "???",
  "greeting.hello": "Привет, Алекс 👋",
  "rightPane.language": "Язык",
  "rightPane.option1": "Опция 1",
  "rightPane.option2": "Опция 2",
  "rightPane.option3": "Опция 3",
  "rightPane.showKeys": "Показывать ключи",
  "ui.mode.dark": "Тёмная тема",
  "ui.mode.light": "Светлая тема",
  "settings.title": "Настройки",
  "settings.close": "Закрыть",
  "settings.debug.title": "Отладка",
  "settings.debug.showKeys.label": "Показывать ключи переводов",
  "settings.debug.showKeys.help":
    "Если включено, каждая строка добавит в конец свой ключ в квадратных скобках.",
};
